### ISSUE TITLE
CORS 발표때 나왔던 질문과 답변

### ISSUE THREAD

**Issue by eod940** [ValueWith/ValueWith_Study#4]
**개요**
12월 23일 토요일 진행된 @geniee1220 님의 CORS 발표 관련 질문과 답입니다.
확인해주시고 수정 필요하면 말씀해주세요.

**질문과 답**
1. 허용되지 않은 http 메서드로 요청시 cors가 뜨나요?
    - 다른 error가 뜹니다.

2. Preflight 요청은 네트워크 연결의 3way handshake랑 개념이 비슷해 보이는데 개념이 같은 건가요?
    - 해당 개념과는 다르다고 생각합니다.

3. CORS가 뜨면 서버에서 요청처리를 안해주는거 아닌가요?
    - Preflight가 없이 다이렉트로 서버에 꽂힌 요청은 서버에서 모든 동작이 완료 된 후, 결과 반환 직전에 브라우저에서 CORS Error를 뱉습니다.
    - 따라서 이러한 상황을 방지하고자 CORS 설정이 안되어 있는 서버들을 보호하기 위해 CORS spec에 예비 요청(preflight request)을 포함시켰다고 합니다.

4. Preflight 단계에서 CORS가 뜨나요?
    - 네

5. 단순 요청의 type은 왜 3개인가요?
    - 그부분은 잘 모르겠습니다. 추가적으로 학습해야 할 부분인 것 같습니다.

 6. credential request에서 credentials = true를 클라이언트에서 요청하나요?
    - 네

 7.  포워드 프록시 서버가 Tweaver에도 구현되어 있는걸 새롭게 알았습니다.
    - 네

**Comment by geniee1220** [comment]
단순 요청의 type은 왜 3개 인가요? ->  Get, Post, Head 세 개의 메서드 중에 Head는 어떤 메서드인가요?

Head 메서드는 Get 메서드르 요청했을 때 돌아올 **헤더** 부분만 요청하는 메서드입니다. 서버에서는 메세지 본문을 반환해서는 안 됩니다.
Response 헤더에는 Get 메서드로 요청했을 때와 동일한 메타 데이터가 담기게 됩니다. 
파일의 존재 여부, 상태 및 크기를 점검할 때(Status 200이 떨어지는지 등), 최근 수정 여부를 확인할 때 사용될 수 있습니다.

**Comment by eod940** [comment]
감사합니다!
